# Generated by Django 5.1 on 2024-08-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
