# Generated by Django 5.1 on 2024-11-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartorder_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='razor_pay_order_signature',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='razor_pay_payment_id',
        ),
    ]
